import time
import random
import os
import tiktoken
import litellm
import ollama
import tiktoken
from .model_profiles import load_model_profile
from .usage_log import record_usage


class LLMInvocation:
    def __init__(self, model: str, component: str = "unspecified"):
        self.model = model
        self.component = component

    def _completion_params(self, messages, max_tokens, temperature, **kwargs):
        """Build one LiteLLM request from the model profile and call options."""
        params = {
            "model": self.model,
            "messages": messages,
            "max_tokens": max_tokens,
            "temperature": temperature,
        }
        params.update(load_model_profile(self.model))
        params.update(kwargs)
        api_base = os.environ.get("COGPATH_LLM_API_BASE")
        if api_base:
            params["api_base"] = api_base
        elif self.model.startswith("ollama"):
            params.setdefault("api_base", "http://210.28.134.33:11434")
        return params

    def call_model(self, prompt: dict, max_tokens=4096, temperature=0.2):
        """
        Returns:
            tuple: A tuple containing the response generated by the LLM,
            the number of tokens used from the prompt, and the total number of tokens in the response.
        """
        if "system" not in prompt or "user" not in prompt:
            raise KeyError("The prompt dictionary must contain 'system' and 'user' keys.")

        if prompt["system"] == "":
            messages = [{"role": "user", "content": prompt["user"]}]
        else:
            messages = [
                {"role": "system", "content": prompt["system"]},
                {"role": "user", "content": prompt["user"]},
            ]

        completion_params = self._completion_params(
            messages, max_tokens, temperature, stream=True
        )

        max_retries = int(os.environ.get("COGPATH_LLM_MAX_RETRIES", "5"))
        base_delay = 2  # base delay in seconds

        for attempt in range(max_retries):
            request_started = time.monotonic()
            try:
                response = litellm.completion(**completion_params)
                chunks = []
                for chunk in response:
                    print(
                        chunk.choices[0].delta.content or "", end="", flush=True)
                    chunks.append(chunk)
                    time.sleep(0.01)
                print("\n")
                model_response = litellm.stream_chunk_builder(
                    chunks, messages=messages)
                record_usage(
                    alias=self.model,
                    model_id=completion_params.get("model", self.model),
                    component=self.component,
                    started_at=request_started,
                    usage=model_response.get("usage"),
                    request_id=model_response.get("id"),
                    attempt=attempt + 1,
                )
                return (
                    model_response["choices"][0]["message"]["content"],
                    int(model_response["usage"]["prompt_tokens"]),
                    int(model_response["usage"]["completion_tokens"]),
                )
            except Exception as e:
                record_usage(
                    alias=self.model,
                    model_id=completion_params.get("model", self.model),
                    component=self.component,
                    started_at=request_started,
                    status="error",
                    error_type=type(e).__name__,
                    attempt=attempt + 1,
                )
                delay = base_delay * (2 ** attempt) + random.uniform(0, 1)
                print(f"Rate limit exceeded. "
                      f"Retrying in {delay:.2f} seconds... "
                      f"(Attempt {attempt + 1}/{max_retries})")
                time.sleep(delay)

        raise RuntimeError(
            "Max retries exceeded. Could not complete API call.")



class AzureOpenAIInvocation(LLMInvocation):
    def __init__(self, model: str, base_url: str, api_version: str, ak: str):
        super().__init__(model)
        self.azure_options = {
            "api_base": base_url,
            "api_version": api_version,
            "api_key": ak,
            "custom_llm_provider": "azure",
        }
        
    def call_model(self, prompt: dict, max_tokens=4096, temperature=0.2):
        if "system" not in prompt or "user" not in prompt:
            raise KeyError(
                "The prompt dictionary must contain 'system' and 'user' keys.")

        if prompt["system"] == "":
            messages = [{"role": "user", "content": prompt["user"]}]
        else:
            messages = [
                {"role": "system", "content": prompt["system"]},
                {"role": "user", "content": prompt["user"]},
            ]

        completion_params = self._completion_params(
            messages, max_tokens, temperature, stream=True,
            extra_headers={"X-TT-LOGID": ""}, **self.azure_options
        )
        
        max_retries = 5
        base_delay = 2  # base delay in seconds

        for attempt in range(max_retries):
            try:
                response = litellm.completion(**completion_params)
                chunks = []
                try:
                    for chunk in response:
                        print(
                            chunk.choices[0].delta.content or "", end="", flush=True)
                        chunks.append(chunk)
                        time.sleep(0.01)
                except Exception as e:
                    print(f"Error during streaming: {e}")
                print("\n")
                # fill complete content
                full_content = "".join(
                    chunk.choices[0].delta.content or "" 
                    for chunk in chunks
                )
                
                # calculate token count
                try:
                    encoding = tiktoken.encoding_for_model(self.model)
                    prompt_text = " ".join(msg["content"] for msg in messages)
                    prompt_tokens = len(encoding.encode(prompt_text))
                    completion_tokens = len(encoding.encode(full_content))
                except Exception:
                    prompt_tokens = int(len(" ".join(msg["content"] for msg in messages).split()) * 1.3)
                    completion_tokens = int(len(full_content.split()) * 1.3)
                
                return (full_content, prompt_tokens, completion_tokens)
            except Exception as e:
                delay = base_delay * (2 ** attempt) + random.uniform(0, 1)
                print(f"API Error: {e}")
                print(f"Rate limit exceeded. "
                      f"Retrying in {delay:.2f} seconds... "
                      f"(Attempt {attempt + 1}/{max_retries})")
                time.sleep(delay)

        raise RuntimeError(
            "Max retries exceeded. Could not complete API call.")
